# Generated by Django 4.2.7 on 2023-11-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swag',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
