# Generated by Django 4.2.7 on 2023-11-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swags', '0002_swag_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swag',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
