# Generated by Django 4.2.7 on 2023-11-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_answer_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfig',
            options={'permissions': [('checked_in', 'User completed check-in')]},
        ),
        migrations.AddField(
            model_name='userconfig',
            name='college',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='food',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non-veg', 'Non Vegetarian'), ('starve', 'Starve')], default='starve', max_length=7),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('wm', 'Washing Machine')], default='wm', max_length=10),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='github',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='team',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='tshirt',
            field=models.CharField(choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', 'Double XL'), ('naked', 'Naked')], default='naked', max_length=5),
        ),
        migrations.AddField(
            model_name='userconfig',
            name='year_of_study',
            field=models.IntegerField(default=-1),
        ),
    ]
