# Generated by Django 4.2.7 on 2023-11-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userconfig_options_userconfig_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
