# Generated by Django 4.2.7 on 2023-11-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userconfig_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
