# Generated by Django 4.2.7 on 2023-11-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_userconfig_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userconfig',
            options={},
        ),
        migrations.AddField(
            model_name='userconfig',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
