# Generated by Django 4.2.7 on 2023-11-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_userconfig_options_userconfig_checked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='college',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='course',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='github',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='linkedin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='team',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
